#Dependabot checks for weekly updates in the Maven package ecosystem by scanning the package manifests located in the root directory.
#It creates also tickets with pull request if it finds a necessary update
version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
